enh(article): add dbee
mmngreco/mmngreco.github.io-source pull request #1
Opened 2021-08-01 19:06 UTC by mmngreco

2021-08-01 20:28 UTC, mmngreco reviewed
Some improvements

2021-08-01 20:28 UTC, mmngreco commented on content/articles/2021-08-01-dbee-nvim.md
> +we are ready to make queries to the database.
``
```suggestion
we are ready to make queries to that database.
```

2021-08-01 20:28 UTC, mmngreco commented on content/articles/2021-08-01-dbee-nvim.md
> +We can setup our connection by going to `cn_str` line, selecting the content
```suggestion
We can setup our connection by going to the line where `cn_str` is and select the content
```

2021-08-02 07:09 UTC, KikeM requested changes
Hi Max, 

As requested I have had a look ;)
Pretty useful, I should one day follow you in your path with VIM.

Cheers

2021-08-02 07:09 UTC, KikeM commented on content/articles/2021-08-01-dbee-nvim.md
> +Have you ever had the necessity of check a query while you are writing a python
Have you ever had the necessity to check a query while you are writing a python

2021-08-02 07:09 UTC, KikeM commented on content/articles/2021-08-01-dbee-nvim.md
> +debugging or testing it. That's why I wrote my first vim (well, actually a
Many times I have had the necessity of checking a query while I'm writing,
debugging or testing a function.

2021-08-02 07:09 UTC, KikeM commented on content/articles/2021-08-01-dbee-nvim.md
> +## My using case
## My use case

2021-08-02 07:09 UTC, KikeM commented on content/articles/2021-08-01-dbee-nvim.md
> +process is very annoying.
I have a virtual environment with `SQLAlchemy` and others Python dependencies,
and then I want to check a query from my project. So, I have to open `DBeaver`,
or another SQL client, copy-paste the query there and see the result. This 
process can be very annoying.

2021-08-02 07:09 UTC, KikeM commented on content/articles/2021-08-01-dbee-nvim.md
> +Why I have to open an external program when I already had all what I need in my
Why do I have to open an external program when I already have all that I need in my

2021-08-02 07:09 UTC, KikeM commented on content/articles/2021-08-01-dbee-nvim.md
> +it?
The idea is to define an `engine` using `SQLAlchemy` with a connection string, and
then through `pandas` fetch the data using that engine. Pretty simple, isn't
it?

2021-08-02 07:09 UTC, KikeM commented on content/articles/2021-08-01-dbee-nvim.md
> +Suppose we are writing the following python function:
Let's suppose that we are writing the following python function:

2021-08-02 07:09 UTC, KikeM commented on content/articles/2021-08-01-dbee-nvim.md
> +string, the query used and the output on it. You can easily close the buffer by
string, the selected query and the output fetched from it. You can easily close the buffer by

2021-08-22 10:16 UTC, mmngreco reviewed
@KikeM Many thanks for your feedback. In case you don't know, you can use the "suggestions" button which is perfect for this purpose.

![image](https://user-images.githubusercontent.com/6231413/130347566-f76c6765-2d1f-44a2-9db7-47a8e45f8b41.png)

Thanks! ;-)

2021-08-22 10:16 UTC, asdf8601 commented on content/articles/2021-08-01-dbee-nvim.md
> +Suppose we are writing the following python function:
This is a good one, I realized that I have problems guessing when I should omit "that".

2021-08-22 10:17 UTC, merged